<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ame</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\$\*|^\{[^{]*$|[^@]\{[^{]*$</string>
	<key>foldingStopMarker</key>
	<string>\*\$|.*\}[^}]*$</string>
	<key>name</key>
	<string>Amethyst</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment_line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@[@{}]</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@\s*format)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\s*(\$.*)?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.dollar</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.format</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#filter_escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#gemtest</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#gemstyle</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@\s*length)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\s*(\$.*)?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.dollar</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.length</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment_line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#filter_escaped_char</string>
				</dict>
				<dict>
					<key>match</key>
					<string>leftmargin|rightmargin|spacing|indent</string>
					<key>name</key>
					<string>keyword.other.length</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#gemtest</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#gemstyle</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.macro</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@\s*macro)\s*\{\s*(\w+)\s*\}</string>
			<key>name</key>
			<string>meta.definition.macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@\s*(output|input|include|require|apply|set|ifdef|ifndef|else)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@\s*(format|length|arg|rarg)</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@part)\s*\{\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.heading.1</string>
			<key>end</key>
			<string>\s*\}</string>
			<key>name</key>
			<string>meta.markup.heading.1</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@chapter)\s*\{\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.heading.2</string>
			<key>end</key>
			<string>\s*\}</string>
			<key>name</key>
			<string>meta.markup.heading.2</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@section)\s*\{\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.heading.3</string>
			<key>end</key>
			<string>\s*\}</string>
			<key>name</key>
			<string>meta.markup.heading.3</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@subsec)\s*\{\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.heading.4</string>
			<key>end</key>
			<string>\s*\}</string>
			<key>name</key>
			<string>meta.markup.heading.4</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@sub2sec)\s*\{\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.heading.5</string>
			<key>end</key>
			<string>\s*\}</string>
			<key>name</key>
			<string>meta.markup.heading.5</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@sub3sec)\s*\{\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.heading.6</string>
			<key>end</key>
			<string>\s*\}</string>
			<key>name</key>
			<string>meta.markup.heading.6</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@sub4sec)\s*\{\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.heading.7</string>
			<key>end</key>
			<string>\s*\}</string>
			<key>name</key>
			<string>meta.markup.heading.7</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@em)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.style</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.italic</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.markup.italic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@strong)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.style</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.bold</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.markup.bold</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@pre)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>markup.raw</string>
			<key>end</key>
			<string>^\s*\}|[^@]\}|\}</string>
			<key>name</key>
			<string>meta.markup.preformatted</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>@[@{}]</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.stylemodifier</string>
				</dict>
			</dict>
			<key>match</key>
			<string>@\s*\w+\s*((/\s*\w+\s*)*)</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment_block</key>
		<dict>
			<key>begin</key>
			<string>\$\*</string>
			<key>end</key>
			<string>\*\$</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<key>comment_line</key>
		<dict>
			<key>match</key>
			<string>\$.*$</string>
			<key>name</key>
			<string>comment.line.dollar</string>
		</dict>
		<key>filter_escaped_char</key>
		<dict>
			<key>match</key>
			<string>@[RrI].|@[^ ]</string>
			<key>name</key>
			<string>constant.character.escape</string>
		</dict>
		<key>gemstyle</key>
		<dict>
			<key>match</key>
			<string>!?(acro|caption|center|cite|cmd|code|def|double|email|enum|em|file|header|important|huge|kbd|left|large|note|linebreak|opt|pre|roman|right|samp|single|small|strong|tag|thick|thin|tiny|url|var|warning)</string>
			<key>name</key>
			<string>keyword.other.gemstyle</string>
		</dict>
		<key>gemtest</key>
		<dict>
			<key>match</key>
			<string>!?(next|prev|first|last|following|preceding|order|parent\d*|part|chapter|section|subsec|sub[234]sec|contents|try|pass|top|me|myparent|myancestor|break|br|control|@|final|child|order|count|width|text|begins|gem|indent|list|deflist|table|@)</string>
			<key>name</key>
			<string>keyword.other.gemtest</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.amethyst</string>
	<key>uuid</key>
	<string>F66C56DF-B79F-4535-938B-A9F0B68C33A1</string>
</dict>
</plist>
