<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<!-- 
Improvements todo: 
	- Finale scripts sub-syntax
	- Values block syntax
-->
<dict>
	<key>fileTypes</key>
	<array>
		<string>ded</string>
	</array>
	<key>name</key>
	<string>Doomsday Engine Definitions</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#&gt;</string>
			<key>end</key>
			<string>&lt;#</string>
			<key>name</key>
			<string>long_comment</string>
			<key>name</key>
			<string>comment.block.doomsdaydefns</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quoted_string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<!--<dict>
			<key>include</key>
			<string>#def_single</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifier</string>
		</dict>-->
		<dict>
			<key>include</key>
			<string>#hex_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>punctuation.terminator.statement.doomsdaydefns</string>	
		</dict>
		<dict>
			<key>match</key>
			<string>\|</string>
			<key>name</key>
			<string>keyword.operator.doomsdaydefns</string>	
		</dict>
		<dict>
			<key>match</key>
			<string>ID</string>
			<key>name</key>
			<string>entity.name.variable.doomsdaydefns</string>
		</dict>
		<!-- <dict>
			<key>begin</key>
			<string>(?i)(Copy|\*|)\s*(Header|Flag|Episode|Hub|Map|Map\sInfo|Exit|Mobj|Thing|State|Sprite|Light|Material|Layer|Stage|Model|Md2|Sub|Sound|Music|Sky|Layer\s1|Layer\s2|Info|Sky\sModel|Text|Texture\sEnvironment|Composite\sBitmapFont|Values|Detail|Reflection|Generator|Finale|InFine|Decoration|Group|Line|Sector|)\s*({|$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.doomsdaydefns</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.doomsdaydefns</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.doomsdaydefns</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.doomsdaydefns</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.doomsdaydefns</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.doomsdaydefns</string>
				</dict> -
			</array> 
		</dict> -->
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>(?i)(Copy|\*|)\s*(Header|Flag|Episode|Hub|Map|Map\sInfo|Exit|Mobj|Thing|State|Sprite|Light|Material|Layer|Stage|Model|Md2|Sub|Sound|Music|Sky|Layer\s1|Layer\s2|Info|Sky\sModel|Text|Texture\sEnvironment|Texture|Composite\sBitmapFont|Values|Detail|Reflection|Generator|Finale|InFine|Decoration|Group|Line|Sector)(\s+(Mods)\s+("[^""]*")|)\s*({|$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.doomsdaydefns</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.doomsdaydefns</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.doomsdaydefns</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.doomsdaydefns</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.doomsdaydefns</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.doomsdaydefns</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
<!-- 	<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(True|False)\b</string>
			<key>name</key>
			<string>constant.language.doomsdaydefns</string>
		</dict>
		<key>def_condition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.doomsdaydefns</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign-script.doomsdaydefns</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.doomsday</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(condition)\s*(:)(.*)</string>
			<key>name</key>
			<string>meta.definition.singleline.condition</string>
		</dict>
		<key>def_scripted</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdaydefns</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign-script.doomsdaydefns</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.doomsday</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>([-@".\w]+)\s*(\$:)(.*)</string>
			<key>name</key>
			<string>meta.definition.singleline.scripted.doomsdaydefns</string>
		</dict>
 		<key>def_scripted_expr</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdaydefns</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.doomsdaydefns</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.doomsday</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>([-@".\w]+)\s*(\$=)(.*)$</string>
		</dict>
		<key>def_single</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdaydefns</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign.doomsdaydefns</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.raw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([-@".\w]+)\s*(:)(.*)</string>
			<key>name</key>
			<string>meta.definition.singleline</string>
		</dict> -->
		<key>def_value</key>
		<dict>
			<key>match</key>
			<string>([-@".\w ]+)(=)\s*(.*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdaydefns</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign.doomsdaydefns</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quoted_string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#hex_number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#line_comment</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.definition.singlevalue</string>
		</dict>
<!--		<key>identifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[-@\w.]+\s*(?=[=&lt;])</string>
					<key>name</key>
					<string>variable.language.doomsdaydefns</string>
				</dict>
			</array>
		</dict>
     	<key>implicit_group</key>
		<dict>
			<key>match</key>
			<string>([-@A-Za-z0-9_.]+)\s+(?={)</string>
			<key>name</key>
			<string>variable.language.doomsdaydefns</string>
		</dict> -->
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(Header|Include|IncludeIf|SkipIf|Copy|Not)\b</string>
			<key>name</key>
			<string>keyword.control.doomsdaydefns</string>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.doomsdaydefns</string>
		</dict>
		<key>hex_number</key>
		<dict>
			<key>match</key>
			<string>\b[-+]?0[xX][0-9A-Fa-f]+\b</string>
			<key>name</key>
			<string>constant.numeric.hexadecimal.doomsdaydefns</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\b[-+]?[0-9]*\.?[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.doomsdaydefns</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.operator.assignment.doomsdaydefns</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>keyword.operator.doomsdaydefns</string>
				</dict>
			</array>
		</dict>
		<key>quoted_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.doomsdaydefns</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>''</string>
					<key>name</key>
					<string>constant.character.doublequote.doomsdaydefns</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.doomsdaydefns</string>
				</dict>
			</array>
		</dict>
<!--	<key>typed_group</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdaydefns</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) ^\s* ([-@A-Za-z0-9_.]+) \s+ ([-"@A-Za-z0-9_.]+)</string>
			<key>name</key>
			<string>entity.name.type.class.doomsdaydefns</string>
		</dict> -->
	</dict>
	<key>scopeName</key>
	<string>source.doomsdaydefns</string>
	<key>uuid</key>
	<string>d176f287-b93c-4569-8804-5cd9bd3b2437</string>
</dict>
</plist>
