<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dei</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~D</string>
	<key>name</key>
	<string>Doomsday Info</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#list</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x) (script) \s+ ([-@".\w]+) \s+ ([-@".\w]+) \s* ({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.attribute-value.doomsdayinfo</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.doomsdayinfo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.doomsdayinfo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.script.doomsday</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.doomsday</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(script)\s*({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.doomsdayinfo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.doomsdayinfo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.script.doomsday</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.doomsday</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(vertex|fragment)\s*(=)\s*"</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign.doomsdayinfo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>meta.embedded.glsl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.glsl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#quoted_string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#def_condition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#def_scripted_expr</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#def_scripted</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#def_single</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifier</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#typed_group</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#implicit_group</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.doomsdayinfo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.scope.doomsdayinfo</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(True|False)\b</string>
			<key>name</key>
			<string>constant.language.doomsdayinfo</string>
		</dict>
		<key>def_condition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign-script.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.doomsday</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(condition)\s*(:)(.*)</string>
			<key>name</key>
			<string>meta.definition.singleline.condition</string>
		</dict>
		<key>def_scripted</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign-script.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.doomsday</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>([-@".\w]+)\s*(\$:)(.*)</string>
			<key>name</key>
			<string>meta.definition.singleline.scripted.doomsdayinfo</string>
		</dict>
		<key>def_scripted_expr</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.doomsday</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>([-@".\w]+)\s*(\$=)(.*)$</string>
		</dict>
		<key>def_single</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.raw</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([-@".\w]+)\s*(:)(.*)</string>
			<key>name</key>
			<string>meta.definition.singleline</string>
		</dict>
		<key>def_value</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assign.doomsdayinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quoted_string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#line_comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constants</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>([-@".\w]+)\s*(=)\s*(.*)</string>
			<key>name</key>
			<string>meta.definition.singlevalue</string>
		</dict>
		<key>identifier</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[-@\w.]+\s*(?=[=&lt;])</string>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
			</array>
		</dict>
		<key>implicit_group</key>
		<dict>
			<key>match</key>
			<string>([-@A-Za-z0-9_.]+)\s+(?={)</string>
			<key>name</key>
			<string>variable.language.doomsdayinfo</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>\b(group|script|inherits|condition)\b</string>
			<key>name</key>
			<string>keyword.control.doomsdayinfo</string>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.doomsdayinfo</string>
		</dict>
		<key>list</key>
		<dict>
			<key>begin</key>
			<string>&lt;</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.array.doomsdayinfo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.array.doomsdayinfo</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quoted_string</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.array.doomsdayinfo</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\b[-+]?\.?[_0-9]+</string>
			<key>name</key>
			<string>constant.numeric.doomsdayinfo</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.operator.assignment.doomsdayinfo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>keyword.operator.doomsdayinfo</string>
				</dict>
			</array>
		</dict>
		<key>quoted_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.doomsdayinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.doomsdayinfo</string>
				</dict>
			</array>
		</dict>
		<key>typed_group</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.language.doomsdayinfo</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) ^\s* ([-@A-Za-z0-9_.]+) \s+ ([-"@A-Za-z0-9_.]+)</string>
			<key>name</key>
			<string>entity.name.type.class.doomsdayinfo</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.doomsdayinfo</string>
	<key>uuid</key>
	<string>CF5BEEB9-0B49-4DE2-AB4F-46F5EC6182CE</string>
</dict>
</plist>
