<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>de</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~D</string>
	<key>name</key>
	<string>Doomsday Script</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.class.doomsday</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.doomsday</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.doomsday</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.doomsday</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.doomsday</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x) ^ \s* (record) \s+ ([.a-zA-Z0-9_]+) \s* (\() (([.a-zA-Z0-9_]+)?) (\))</string>
			<key>name</key>
			<string>meta.class.doomsday</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expressions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#statements</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x) ^\s* (def) \s+ ([A-Za-z_][0-9A-Za-z_.]*) \s* (\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.def.doomsday</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.doomsday</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.doomsday</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.doomsday</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.method.with-arguments.doomsday</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[_a-zA-Z])</string>
					<key>end</key>
					<string>(?=[,)])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter.function.doomsday</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([_a-zA-Z]\w*)</string>
						</dict>
						<dict>
							<key>match</key>
							<string>=</string>
							<key>name</key>
							<string>keyword.operator.assign.doomsday</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.doomsday</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#storagemod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|elsif|end|while|for|break|continue|pass|return|throw|try|catch)\b</string>
			<key>name</key>
			<string>keyword.control.doomsday</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>array_brackets</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bracket.doomsday</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bracket.doomsday</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.doomsday</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>keyword.operator.slice.doomsday</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>class_name</key>
		<dict>
			<key>match</key>
			<string>\b[A-Z][A-Za-z0-9_]{2,}\b</string>
			<key>name</key>
			<string>support.class.doomsday</string>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(True|False|None|Pi)\b</string>
			<key>name</key>
			<string>constant.language.doomsday</string>
		</dict>
		<key>dict_brackets</key>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.dict.doomsday</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.dict.doomsday</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.doomsday</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:</string>
					<key>name</key>
					<string>punctuation.separator.key-value.doomsday</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_multi</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_single</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special_vars</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function_call</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#scope_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parentheses</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dict_brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array_brackets</string>
				</dict>
			</array>
		</dict>
		<key>function_call</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.doomsday</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(serialize|deserialize|locals|len|dictkeys|dictvalues|File|Text|Time|Number|Record|typeof|dir|eval|floor|timedelta|subrecords|members|globals)\s*(?=\()</string>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>match</key>
			<string>#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.doomsdayinfo</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\b[-+]?(0[xX][0-9A-Fa-f_]+|\.?[0-9][0-9_.]*)</string>
			<key>name</key>
			<string>constant.numeric.doomsday</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>[-+*/%:?=&lt;&gt;!]=|[-+*/%=&lt;&gt;]|-&gt;|\b(not|in|and|or|record)\b|\.</string>
			<key>name</key>
			<string>keyword.operator.doomsday</string>
		</dict>
		<key>parentheses</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.parentheses.doomsday</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.parentheses.doomsday</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>scope_name</key>
		<dict>
			<key>match</key>
			<string>\b[A-Za-z0-9_]+\.</string>
			<key>name</key>
			<string>support.variable.doomsday</string>
		</dict>
		<key>special_vars</key>
		<dict>
			<key>match</key>
			<string>\b(self|__[A-Za-z_][0-9A-Za-z_]*__)\b</string>
			<key>name</key>
			<string>variable.language.doomsday</string>
		</dict>
		<key>statements</key>
		<dict>
			<key>match</key>
			<string>\b(import|export|del|print|record)\b</string>
			<key>name</key>
			<string>keyword.other.doomsday</string>
		</dict>
		<key>storagemod</key>
		<dict>
			<key>match</key>
			<string>\b(const)\b</string>
			<key>name</key>
			<string>storage.modifier.doomsday</string>
		</dict>
		<key>string_multi</key>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.quoted.triple.doomsday</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.doomsday</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.doomsday</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.doomsday</string>
				</dict>
			</array>
		</dict>
		<key>string_single</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.doomsday</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.doomsday</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.doomsday</string>
	<key>uuid</key>
	<string>EE9BDAB7-EAE0-495F-AA7B-2DC1227B8A09</string>
</dict>
</plist>
